### PR TITLE
TASK-85: Modal Component

### LINKED ISSUE #301: TASK-85: Reusable Modal Component
**Task Description**

As a developer, I want to have a reusable modal component so that it may be used in pages that need modals.

**Subtasks**
- [ ] 85.1 Reusable modal component with rounded corners, x button, and common styling across all modals
- Specific modals for Friends:
   - [ ] 85.2 Reusable friend modal component with [1 button](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58839) exists
   - [ ] 85.3 Reusable friend modal component with [2 buttons](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1596%3A4543) exists

**Acceptance Criteria**
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] Must match mockups (see subtasks)

**NOTE**
The tickets blocked by this task is a soft-block as those tickets can technically implement their own modals.

### PR DESCRIPTION
**Pull request by cristian-aldea**
closes #301

**NOTE: Changes in app.tsx are TEMPORARY, and will be reverted before the pr is merged. See commit messages for details.**

This pr aims to create a generic modal component for use throughout the app. It also creates a FriendModal which will be useful for upcoming tickets.

How to test:
- There is some temporary code I added in app.tsx that you can play around with to try the modals
```tsx
      {userData && true && (
        <FriendModal
          open={open}
          setOpen={setOpen}
          paperClasses="asdf-asdf"
          user={userData.user as User}
          button1Text="hello"
          button1OnClick={() => {
            console.log('asdf');
          }}
          button2Text="hello"
          button2OnClick={() => {
            console.log('asdf');
          }}
        ></FriendModal>
      )}
      {false && (
        <MullModal open={open} setOpen={setOpen}>
          Hello There!
        </MullModal>
      )}
```
- When checking out to my branch for the first time, once you log in a refresh the page, you should see a modal pop up with your username and picture, and two buttons. You can play around with the props of the FriendModal to change the content.
image

- If you want to see how the generic MullMoral component looks, you can set `{userData && true && (` to `{userData && false && (` to hide the FriendModal, and set `{false && (` to `{true && (` to show the MullModal. You can insert any jsx content in the modal, so go wild and try out stuff

image

### CODE REVIEW

**Review by cindyslittleplanet — APPROVED** [review]
Have a few comments about the styling, but overall it looks good! 🚀 
- The text inside each button should not be bold
- The username should be in a bigger font than the button font
- It would look nicer if the buttons had the same width despite having different length of text


image

**Comment by cristian-aldea** [comment]
> Have a few comments about the styling, but overall it looks good! 🚀
> 
> * The text inside each button should not be bold
> * The username should be in a bigger font than the button font
> * It would look nicer if the buttons had the same width despite having different length of text

- I noticed in the mockups that the "alt-style" button never had bold text, so I removed the bold on there
- The username on the friend modal is now slightly bigger
- I reduced the padding and added a min-width to the button, so that small changes in text don't change the button size much. I also set stretch for the flex alignment of the buttons in the modal, so they will always have the same width.

**Comment by cristian-aldea** [comment]
Addressed your concerns @cindyslittleplanet 
image

lemme know what you think

**Review by RGPosadas — APPROVED** [review]
Thank you for the speedy and robust implementation! LGTM! Though Dialog creates some noise while running the frontend unit tests.

**Subtasks**
- [x] 85.1 Reusable modal component with rounded corners, x button, and common styling across all modals
- Specific modals for Friends:
   - [x] 85.2 Reusable friend modal component with [1 button](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58839) exists
   - [x] 85.3 Reusable friend modal component with [2 buttons](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1596%3A4543) exists

**Acceptance Criteria**
- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every new component and function
- [x] Must match mockups (see subtasks)

**Pull request merged**
