### PR TITLE
BUG-19: Profile page profile picture is not always a circle

### LINKED ISSUE #254: BUG-19: Profile page profile picture is not always a circle
**Describe The Bug**

When a vertical image is uploaded as a user's profile picture, the Profile Page squishes the photo vertically and it no longer is a circle.

**To Reproduce**

1. Have a user
2. Go to their profile page
3. Edit their profile to upload a vertical profile picture
4. Go back to profile page and you will see that the image is squished

**Expected Behavior**

* Profile picture stays as a circle.
* Note that on Edit Profile and in any of the chatting pages, the profile photo is NOT squished, and the bug only happens on Profile Page.

* Edit Profile --> circle
image

* Profile Page --> oval
image

* Announcements --> circle
image

* Profile Page (what it should be) --> circle
image

**Bug Handling Strategy**
- [ ] Fix it now
- [x] Fix it later

### PR DESCRIPTION
**Pull request by leojrsilao**
This PR closes #254 

To test this PR:

1. Go to Profile Page
2. Edit image and choose a long vertical image.
3. Update image
4. Image is a circle and not oval shaped anymore.

### CODE REVIEW

**Review by cristian-aldea — CHANGES_REQUESTED** [review]
I'm afraid this styling doesn't fix the circle issue for very tall images.

image

Simply add `min-height: 5rem;` to the `.user-profile-picture` class. Would also be good to make it into a variable but that's up to you.

image

Result with my suggested change:
image

**Review by cristian-aldea — APPROVED** [review]
I'm approving to avoid blocking this PR, since I might not be available later today, but please add that line I suggested @leojrsilao

**Review by JimLau49 — APPROVED** [review]
LGTM !

**Comment by cristian-aldea** [comment]
My mistake @leojrsilao, I forgot to properly update my local branch, I didn't have the issue once I was updated properly. Thanks for implementing my suggestion but it ended up not being needed haha

**Pull request merged**
