### PR TITLE
TASK-26: Display model results

### LINKED ISSUE #191: TASK-56: Display Model results
**Task Description**

As a developer, I want to display icons over detections from the model so that users can have visual feedback when pointing their camera at objects with the ML tool.

**Extra Description**

This ticket depends on data from #190, but that doesn't mean it can't be started, once the data type of a DetectionResult is defined, the implementation for this ticket can be started on mock data.

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/?node-id=533%3A7886)

### PR DESCRIPTION
**Pull request by ys-lin**
closes #191 

This PR aims to display waste categories detection results with 4 different SVG icons.
Currently, we only have a few classes/types that can be detected:  `bottle`, `box`, `food`,  and `tin can`.

These objects are then categorized according to what we consider to be generally the appropriate way to dispose of them:
1. Recyclable
2. Compostable
3. Trash
4. E-Waste (currently no proper icon, so we've chosen to use the default circle icon)

Please have a look at [this mapping](https://github.com/RGPosadas/Mull/blob/develop/apps/mull-ui/src/app/services/maps.ts#L22) for details.

The detection results might not be perfect, so if you run into issue where your object isn't being detected, keep in mind that more training will be needed for the model to have better performance.

To test this PR please follow the steps listed in #202. You should see detection result icons showing on top of the detected object(s):

image

### CODE REVIEW

**Comment by JimLau49** [comment]
Currently testing the PR, im getting a lot of objects labeled as recycling even if they are part of the other categories you listed in the PR.
Ex: im getting tin cans + boxes labeled as recyclable instead of their respective SVGs

image

If there are working examples where i can test for metals or trash let me kno @ys-lin  
Thanks

**Comment by cristian-aldea** [comment]
> Currently testing the PR, im getting a lot of objects labeled as recycling even if they are part of the other categories you listed in the PR.

I think there's a misunderstanding. Each type of object is then also categorized according to if its typically recyclable, compostable, etc.

Please have a look at https://github.com/RGPosadas/Mull/blob/develop/apps/mull-ui/src/app/services/maps.ts#L22 for details. Boxes and tin cans are considered recyclable, from your picture everything seems to be working as intended.

I've updated the pr message to clarify this

**Review by leojrsilao — APPROVED** [review]
Very nice!! LGTM! 🚀 
Just noticed that there's no unit test for the onClick, but its at the minimum coverage we need, if you want you can also add the unit test for it. 
image

image

**Review by JimLau49 — APPROVED** [review]
LGTM good work

**Review by bit172 — APPROVED** [review]
LGTM! The only concern is that the browser seems to freeze while the detection is happening, maybe some sign that it's loading would be good.

**Comment by cristian-aldea** [comment]
> Very nice!! LGTM! 🚀
> Just noticed that there's no unit test for the onClick, but its at the minimum coverage we need, if you want you can also add the unit test for it.

Good observation, just letting you know thought that this whole page is temporary, and the onclick and image will be replaced with a camera feed in #33. We felt that testing temporary code wasn't necessary

**Pull request merged**
