### PR TITLE
Update prettier version and config

### PR DESCRIPTION
**Pull request by cristian-aldea**
Also formatted and linted the code.

### CODE REVIEW

**Review by osahtout — DISMISSED** [review]
Can confirm that the width has increase and prettier works

**Review by cindyslittleplanet — DISMISSED** [review]
LGTM!
Prettier runs and a larger width can be seen as the code doesn't trail unnecessarily to the next line.

**Review by ghiobi — APPROVED** [review]
Great Müll type example from the lib and reformatting.

**Comment by ghiobi** [comment]
Do you guys have a commit format to follow. Maybe something like https://github.com/commitizen/cz-cli could be followed? #suggestion

**Comment by cristian-aldea** [comment]
> Do you guys have a commit format to follow. Maybe something like https://github.com/commitizen/cz-cli could be followed? #suggestion

We had a wiki which detailed our format for commits, but an automated system like the one you linked could be interesting, I'll look into it

**Review by osahtout — APPROVED** [review]
Still working as expected

**Review by cindyslittleplanet — APPROVED** [review]
Looking good!

**Pull request merged**
