### PR TITLE
US-7.4: View Other User Profiles

### LINKED ISSUE #270: US-7.4: View Other User Profiles
**User Story Description**

As a user, I want to see other users’ profiles so that I may see their profile and events that they’ve participated in.

**User Acceptance Flow**
1. UserA logs in
1. UserA sees UserB's profile page

**Note**: You can hardcode it so that it will check the relationship between user 1 (current user) and user 2.

**Acceptance Criteria**

- [ ] User Acceptance Flow is respected
- [ ] There must exist an automated Cypress acceptance test which tests the user acceptance flow
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data
- [ ] Must match mockups:
   - [Add Friend ](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58846)view
   - [Pending](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58851) view
   - [Friends](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58834) view
   - [Remove Friend modal](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58839) view

### PR DESCRIPTION
**Pull request by RGPosadas**
This PR closes #270 

To test:
* Hardcoded URL:
   * Head on over to `/user/user.id` and check if the user's profile and their relationship with you is accurate with respect to the database
* Natural user flow:
  * ChatBubbleList component: Go to any messaging page and click on an avatar
  * ContactRow component: Go to My Friends and click on a user's row
  * ContactRow FriendModal: When a button is 'View Profile'

### CODE REVIEW

**Review by cindyslittleplanet — COMMENTED** [review]
I found two smol issues: 
1) If the user does not have any events in their portfolio, there should be a something to say that there is nothing instead of a blank page
image

2) The number of friends in the profile header should show the True Friends instead of all friends (pending + true), for example, I have 3 pending and 1 true friend
image


Except that, linting and all test pass!

**Comment by RGPosadas** [comment]
> 1. If the user does not have any events in their portfolio, there should be a something to say that there is nothing instead of a blank page

Thanks for catching this! I've added a simple message

> 2. The number of friends in the profile header should show the True Friends instead of all friends (pending + true), for example, I have 3 pending and 1 true friend

I've modified `friendCount` to use `getTrueFriends`

**Review by cindyslittleplanet — APPROVED** [review]
Thank you for addressing my smol issues! Everything LGTM now!

**Acceptance Criteria**

- [x] User Acceptance Flow is respected
- [x] There must exist an automated Cypress acceptance test which tests the user acceptance flow
- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every new component and function
- [x] The application should still work with seeded data
- [x] Must match mockups:
   - [Add Friend ](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58846)view
   - [Pending](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58851) view
   - [Friends](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58834) view
   - [Remove Friend modal](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58839) view

**Review by leojrsilao — CHANGES_REQUESTED** [review]
Found 1 small issue, 

If User 1 adds User 2 then User 2 adds User 1, the status says 'Pending', but the User 1 already added User 2, it should instantly say, 'Friends' and the number of Friends should be incremented by 1.  
I think an easy fix would be to use `window.location.reload();` to refetch the query from the db. 

Other than that, LGTM! 
Linter, e2e and unit tests passes.
- [x] User Acceptance Flow is respected
- [x] There must exist an automated Cypress acceptance test which tests the user acceptance flow
- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every new component and function
- [x] The application should still work with seeded data
- [x] Must match mockups:
   - [Add Friend ](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58846)view
   - [Pending](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58851) view
   - [Friends](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58834) view
   - [Remove Friend modal](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1793%3A58839) view

**Review by leojrsilao — APPROVED** [review]

**Pull request merged**
