### PR TITLE
Fix: Chat Page Inputs

### PR DESCRIPTION
**Pull request by r-saba**
After discussion with some of the team, we agreed to remove swipeable routes for chat pages due to a known issue with position fixed and CSS transform.

This PR does the following:
- Remove swipeable routes from messages so that we can have a `position: fixed` chat input in message pages.
- Rename `MessagePage` to `ChatPagesHeader`.
- Move chat input into `AnnouncementsPage` page and remove it from `ChatPagesHeader` . This allows each chat page to control the behaviour of the chat input instead of having to do so based on the URL.
- Add logic to create default channels when a new event is created. Needed for #156 and #185

### CODE REVIEW

**Review by bit172 — CHANGES_REQUESTED** [review]
Looks Good! Just a small visual bug on mobile.
This might be related to #238 but the scroll should be on the chat list and not the page. Not a blocker. @ys-lin, make sure you implement the scrollable part.
image


The input box shifted to the right on mobile.
image

**Comment by r-saba** [comment]
> Looks Good! Just a small visual bug on mobile.

Thanks, fixed the visual bug.

> This might be related to #238 but the scroll should be on the chat list and not the page. Not a blocker. @ys-lin, make sure you implement the scrollable part.

We can keep it in the page too, that way each page has finer control over it. In announcements page I want to hide it when the user is not a host for example. Yes, this doesn't block this PR but we should agree on it for #238.

**Review by bit172 — APPROVED** [review]
LGTM!

**Review by leojrsilao — APPROVED** [review]
LGTM 🚀 🚀 ! 
Nice refactoring of code in the frontend, and adjusted logic for event creations with default channels in the backend
- Newly created events now have default channels
- Unit Tests and Linters pass in the front end and backend

**Pull request merged**
