### PR TITLE
TASK-77: View Other User Profiles Backend

### LINKED ISSUE #275: TASK-77: View Other User Profiles Backend
**Task Description**

As a developer, I want to setup the user-relationship queries to connect to the frontend.

**Acceptance Criteria**

- [ ] getUserRelationship query exists and query the appropriate relationship between the logged in user has with the other user
- [ ] Security is handled in the backend
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every new component and function
- [ ] The application should still work with seeded data

**Hint**

image
The easiest way to get a `user-relationship` query for this ticket seems to check the friendlists of the two users:
* If A has B in their friendlist, then A sent B a friend request (AB is in the table)
* If B has A in their friendlist, then B sent A a friend request (BA is in the table)
* If both A and B have each other as friends, then they are friends (AB + BA are in the table)

### PR DESCRIPTION
**Pull request by RGPosadas**
This PR closes #275 

**How To Test**
- Use the addFriend mutation to add rows to the friends pivot table using your favourite GQL playground
- Ensure you have enough users to test the UserRelationship enum (FRIENDS, ADDED_ME, PENDING_REQUEST, and NONE)

### CODE REVIEW

**Review by bit172 — APPROVED** [review]
LGTM! 🚀 Everything seems to work. The only thing that I noticed is that the seeder doesn't actually make everyone a full friend. If you want to fix it in this PR it should be really quick. Let me know if that's what you want to do.

- [x] getUserRelationship query exists and query the appropriate relationship between the logged in user has with the other user
- [x] Security is handled in the backend
- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every new component and function
- [x] The application should still work with seeded data

**Comment by RGPosadas** [comment]
@bit172 I've quickly added a oneliner to the seeder, so now we have some true friends in the seeded data.

**Review by leojrsilao — CHANGES_REQUESTED** [review]
I noticed something that can be updated, a user shouldn't be able to add himself with the addFriend mutation. Other than than LGTM, mutation and queries function as intended!

**Comment by RGPosadas** [comment]
@leojrsilao Thanks for catching that, I've added a check + test for it!

**Review by leojrsilao — APPROVED** [review]

**Pull request merged**
